language: c

# allow containerized build
sude: false 

# Build deps
addons:
  apt:
    packages:
    - rpm
    - devscripts
    - debhelper

# before build script, run autoreconf
before_script: ./autogen.sh

# Default is "./configure && make && make test", but no tests yet
script: 
  - "./configure && make"
  - make rpm
  - make deb
