# Site settings
title: libzbxpgsql
email: ryan@cavaliercoder.com
description: > # this means to ignore newlines until "baseurl:"
  libzbxpgsql is a comprehensive PostgreSQL monitoring module for the Zabbix
  agent.
  
baseurl: "/libzbxpgsql"
url: "http://cavaliercoder.com"
repository: https://github.com/cavaliercoder/libzbxpgsql
twitter_username: cavaliercoder
github_username:  cavaliercoder

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  docs:
    output: true