# Site settings
title: libzbxpgsql
email: ryan@cavaliercoder.com

summary: PostgreSQL monitoring for Zabbix
description: >
  libzbxpgsql is a comprehensive PostgreSQL discovery and monitoring module for
  the Zabbix monitoring agent written in C.

baseurl: "/libzbxpgsql"
url: "http://cavaliercoder.com"
repository: https://github.com/cavaliercoder/libzbxpgsql
twitter_username: cavaliercoder
github_username:  cavaliercoder

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  docs:
    output: true